name: CMake on multiple platforms

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to build"
        required: true
        default: "master"
        type: string
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        include:
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++

          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++

          - os: ubuntu-24.04-arm
            c_compiler: gcc
            cpp_compiler: g++

          - os: macos-latest
            c_compiler: clang
            cpp_compiler: clang++

          - os: macos-15-intel
            c_compiler: clang
            cpp_compiler: clang++

          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Configure CMake
        run: >
          cmake -B build
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
          -DCMAKE_BUILD_TYPE=Release
          -S .

      - name: Build
        run: cmake --build build --config Release

      - name: Test
        working-directory: build
        run: ctest --build-config Release --output-on-failure

      - name: Install
        run: cmake --install build --prefix install --config Release
