name: CMake on multiple platforms

on:
  push:
    branches: ["master"]
  

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        include:
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
          - os: macos-latest
            c_compiler: clang
            cpp_compiler: clang++
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure CMake
        run: >
          cmake -B build
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
          -DCMAKE_BUILD_TYPE=Release
          -S .

      - name: Build
        run: cmake --build build --config Release

      - name: Test
        working-directory: build
        run: ctest --build-config Release --output-on-failure

      - name: Install
        run: cmake --install build --prefix install --config Release
