
name: Debug + Sanitizers

on:
  push:
    branches: ["master"]
    paths:
      - "src/**"
      - "include/**"
      - "tests/**"
      - "CMakeLists.txt"
      - "cmake/**"


jobs:
  sanitizer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Configure CMake
        run: >
          cmake -B build
          -DCMAKE_BUILD_TYPE=Debug
          -DCMAKE_CXX_COMPILER=g++
          -DCMAKE_C_COMPILER=gcc
          -DCMAKE_CXX_FLAGS="-fsanitize=address,undefined -fno-omit-frame-pointer"
          -DCMAKE_C_FLAGS="-fsanitize=address,undefined -fno-omit-frame-pointer"
          -S .

      - name: Build
        run: cmake --build build

      - name: Test
        working-directory: build
        run: ctest --output-on-failure

