name: Build and deploy Doxygen

on:
  push:
    branches: ["master"]
    tags:
      - "v*"

  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Doxygen and Graphviz
        run: sudo apt-get update && sudo apt-get install -y cmake doxygen graphviz

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Generate documentation
        run: doxygen build/Doxyfile

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Download existing Pages artifact
        uses: actions/download-artifact@v5
        continue-on-error: true
        with:
          name: github-pages
          path: site

      - name: Prepare documentation
        run: |
          mkdir -p site

          if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            VERSION="${GITHUB_REF#refs/tags/v}"
            rm -rf "site/${VERSION}"
            mkdir -p "site/${VERSION}"
            cp -r docs/html/. "site/${VERSION}/"
          else
            rm -rf site/latest
            mkdir -p site/latest
            cp -r docs/html/. site/latest/
          fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
